config/routes.rb
Rails.application.routes.draw do
  get 'assigns/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  resources :users, only: [:create, :show, :edit, :update]

  root 'top#index'

  resources :teams, shallow: true do
    resources :assigns
    member do
       get :invite
       post :invite_mail
    end
  end

  resources :reports, only: [] do
    resources :report_comments, only: [:create, :destroy, :edit, :update]
    #   collection do
    #   post :confirm
    # end
  end

  resources :teams do
    resources :reports do
      post :confirm, on: :collection # on: :member
    end
  end

  resources :assigns

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/report_comment.rb
class ReportComment < ApplicationRecord
  belongs_to :report
  validates :comment_content, presence: true
end

app/controllers/report_comments_controller.rb
class ReportCommentsController < ApplicationController
  before_action :set_report, only: [:create, :edit, :update, :edit, :destroy]
  before_action :authenticate_user!

  def create
      @report_comment = @report.report_comments.build(report_comment_params)
      # @report_comment.user_id = current_user.id
      respond_to do |format|
      if @report_comment.save!
        format.js { render :index }
      else
        format.html { redirect_to team_report_path(@report), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @report_comment = @report.report_comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @report_comment = @report.report_comments.find(params[:id])
      respond_to do |format|
        if @report_comment.update(report_comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit_error }
        end
      end
  end
  def destroy
    @report_comment = ReportComment.find(params[:id])
    @report_comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private
  def report_comment_params
    params.require(:report_comment).permit(:report_id, :comment_content)
  end

  def set_report
    @report = Report.find(params[:report_id])
  end
end

app/helpers/report_comments_helper.rb
module ReportCommentsHelper
end

app/views/report_comments/_edit.html.erb
<%= form_with(model: [report, report_comment]) do |form| %>
  <% if report_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% report_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :comment_content, id: "report_comment_comment_content_#{report.id}" %>
    <%= form.label :comment_content %>
  </div>
  <div class="actions">
    <%= form.submit id: "report_comment_comment_content_submit" %>
  </div>
<% end %>

app/views/report_comments/_form.html.erb
<%= form_with(model: [report, report_comment]) do |form| %>
  <% if report_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% report_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :コメント, id: "reports-coment-form__comment_title" %>
    <%= form.text_area :comment_content, id: "reports-comment-form__comment" %>
  </div>
  <div class="actions">
    <%= form.submit  id:"reports-coment-form__comment_submit" %>
  </div>
<% end %>

app/views/report_comments/_index.html.erb
<ul>
  <% report_comments.each do |report_comment| %>
    <% if report_comment.id.present? %>
      <li>
        <div class="comment_content" id = "this_comment_<%= report_comment.id %>"></div>
        <p><%= report_comment.comment_content %></p>


        <span>投稿日時:<%= report_comment.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
        <p><%= link_to "コメント編集", edit_report_report_comment_path(@report, report_comment), remote: true , id: "reports-comment_form__edit" %> |
        <%= link_to "コメント削除", report_report_comment_path(@report, report_comment), method: :delete, remote: true,
                                        data: { confirm: "本当に削除しますか?"}, id: "reports-comment_form__delete"%></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/report_comments/edit.js.erb
$("#this_comment_<%= @report_comment.id %>").replaceWith("<%= j render 'report_comments/edit', report: @report, report_comment: @report_comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/report_comments/index.js.erb
$("#report_comments_area").html("<%= j(render 'report_comments/index', { report_comments: @report_comment.report.report_comments, report: @report_comment.report }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");