config/routes.rb
Rails.application.routes.draw do
  get 'assigns/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  resources :users, only: [:create, :show, :edit, :update]

  root 'top#index'

  resources :teams, shallow: true do
    resources :assigns
    member do
       get :invite
       post :invite_mail
    end
  end

  resources :reports, only: [] do
    resources :report_comments, only: [:create, :destroy, :edit, :update]
    #   collection do
    #   post :confirm
    # end
  end

  resources :teams do
    resources :reports do
      post :confirm, on: :collection # on: :member
    end
  end

  resources :assigns

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :team
  has_many :report_comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :time, presence: true
  validates :content, presence: true
  validates :date, presence: true
  validates :content, length: { maximum: 1000 }

  def self.graphy(reports: [])
    reports = reports || Report.all
    users = reports
      .map(&:user)
      .uniq(&:id)
    users.map { |user| [user.name, user.sum_report_time] }
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_team, only: [:new, :create, :edit, :update, :destroy, :confirm]
  before_action :set_report, only: [:edit, :update, :destroy]
  # before_action :ensure_correct_user, only: [:edit, :update, :destroy, :update]
  PER = 10

  def index
    user_signed_in?
    @user = User.find(current_user.id)
    @user = User.new
    @team = Team.find(params[:team_id])
    @reports = @team.assign_reports.order("id DESC").page(params[:page]).per(PER)
    @graphys = Report.graphy(reports: @reports)
    # @team = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def new
    @team = Team.find(params[:team_id])
    @report = Report.new
    @report.team_id = @team.id
  end

  def create
    @report = current_user.reports.build(report_params)
    @report.team_id = @team.id
    if params[:back]
      render :new
    else
      if @report.save
        redirect_to team_reports_path(@report.team.id), notice: "レポートを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @report = Report.find(params[:id])
    @total_time = @report.user.sum_report_time
    @report_comments = @report.report_comments
    @report_comment = @report.report_comments.build
    @report_comments = @report.report_comments.order(created_at: :asc)
  end

  def edit
  end

  def update
    if @report.update(report_params)
      redirect_to team_reports_path(@team.id), notice: "レポートを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to team_reports_path(@team.id), notice:"レポートを削除しました！"
  end

  def confirm
  # binding.irb
    @report = current_user.reports.build(report_params)
    render :new if @report.invalid?
  end

  private
  def report_params
    params.require(:report).permit(:title, :content, :time,
                                   :date, :place, :image,
                                   :image_cache, :team_id, :user_id)
  end

  def set_team
    @team = Team.find(params[:team_id])
  end

  def set_report
    @report = Report.find(params[:id])
  end

  # def ensure_correct_user
  #   redirect_to teams_path, notice: "権限がありません" if current_user.teams.find_by(id: @team.id).nil?
  #   # redirect_to teams_path, notice: "権限がありません" unless current_user.teams.select { |team| team.id == @team.id }.length == 1
  # end


  # def ensure_correct_user
  #   @report = Report.find_by(id:params[:id])
  #   if @report.user_id != @current_user.id
  #     flash[:notice] = "権限がありません"
  #     redirect_to("/reports")
  #   end
  # end
end




#     route
# view -> controller
#
# params
#
# 1. form -> view
# 2. URL -> route.rb
#
# http://localhost:3000/reports/:id/edit
# http://localhost:3000/reports/34/edit -> params = { id: 34 }
#
# http://localhost:3000/teams/:team_id/reports/:id/edit
# http://localhost:3000/teams/1/reports/34/edit -> params = { id: 34, team_id: 1 }

app/helpers/reports_helper.rb
module ReportsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_team_reports_path(params[:team_id])
    elsif action_name == 'edit'
      team_report_path
    end
  end
end

app/views/reports/_form.html.erb
<div class="container_position">
  <div class="container">
    <div class="contents">
      <%= form_with(model: [@team, @report], local: true, url: choose_new_or_edit ) do |form| %>
        <% if @report.errors.any? %>
          <div id="errors_explanation">
            <h3><%= @report.errors.count %>件のエラーがあります。</h3>
            <ul>
            <% @report.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="report_title">
          <%= form.label :タイトル %>
          <%= form.text_field :title, id: "reports-form__title" %>
        </div><br>
        <div class="report_content">
          <%= form.label :内容 %>
          <%= form.text_area :content, id: "reports-form__content" %>
        </div>
        <br>
        <div class="report_date">
          <%= form.label :実施日 %>
          <%= form.date_select :date, start_year: Date.today.year - 1, class: 'form-control', id: "reports-form__date" %>
        </div>
        <br>
        <div class="report_place">
          <%= form.label :作業場所 %>
          <%= form.text_field :place, class: 'form-control', id: "reports-form__place" %>
        </div>
        <br>
        <div class="report_time">
          <%= form.label :所要時間 %>
          <p><%= form.number_field :time, placeholder: "0.5時間(30分)単位で入力", step: '0.5' , min: '0.5', max: '24', class: 'form-control', id: "reports-form__time" %>時間</p>
        </div>
        <div class="report_image">
          <%= form.label :image %>
          <%= image_tag(@report.image.url) if @report.image && @report.image.url %>
          <%= form.file_field :image %>
          <%= form.hidden_field :image_cache, id: "reports-form__image"%>
        </div>
        <br>
        <div class="actions">
          <%= form.hidden_field :team_id, value: @team.id %>
          <%= form.submit id: "reports-form__submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/confirm.html.erb
<div class="container_position">
  <div class="container">
    <div class="contents">
      <h3>以下の内容で、送信する。</h3>
          <%= form_with(model: [@team, @report], url: team_reports_path, local: true ) do |form| %>
              <%= form.hidden_field :title %>
              <%= form.hidden_field :content %>
              <%= form.hidden_field :date, class: 'form-control' %>
              <%= form.hidden_field :place, class: 'form-control' %>
              <%= form.hidden_field :time, step: '0.5' , class: 'form-control' %>
              <%= form.hidden_field :image_cache, class: 'form-control' %>
              <p>タイトル:<%= @report.title %></p>
              <p>内容:<%= @report.content %></p>
              <p>実施日:<%= @report.date %></p>
              <p>作業場所:<%= @report.place %></p>
              <p>所要時間:<%= @report.time %></p><br>
              <p>画像:<%= image_tag(@report.image.url) if @report.image? && @report.image.url %></p>
            <%= form.submit "登録する", id: "reports--confirm__submit" %>
            <%= form.submit "戻る", name: 'back' %>
          <% end %>
        </div>
      </div>
</div>

app/views/reports/edit.html.erb
<h2>レポートを編集する</h2>
 <%= render 'form' %>

app/views/reports/index.html.erb
<div class="container_position">
  <div class="container">
    <div class="contents">
      <h4 class="reports-index__teams-item">■ チーム名: <%= @team.name %></h4>
        <h3 class="title">レポート一覧</h3>
      　　<nav class="menu">
            <table>
              <tr>
                <th>実行日</th>
                <th>レポートタイトル</th>
                <th>作業場所</th>
                <th>所要時間</th>
                <th>名前</th>
              </tr>
            <% @reports.each do |report| %>
              <tr id=<%="reports-index__reports--#{report.id}"%>>
                <td id=<%="reports-index__reports--#{report.id}__date"%>>
                  <%= report.date %>
                </td>
                <td id=<%="reports-index__reports--#{report.id}__title"%>>
                  <%= report.title %>
                </td>
                <td id=<%="reports-index__reports--#{report.id}__place"%>>
                  <%= report.place %>
                </td>
                <td id=<%="reports-index__reports--#{report.id}__time"%>>
                  <%= report.time %>時間
                </td>
                <td id=<%="reports-index__reports--#{report.id}__user"%>>
                  <%= report.user.name %>
                </td>
                <td><%= link_to '詳細を確認する', team_report_path(@team, report) %></td>
                <% if report.user.id == current_user.id %>
                  <td><%= link_to "レポートを編集する", edit_team_report_path(@team, report) %></td>
                  <td><%= link_to "レポートを削除する", team_report_path(@team, report), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
                <% end %>
              </tr>
            <% end %>
        </table>
    <%= paginate @reports %>
  <br>
  <%= link_to 'レポートを新規作成', new_team_report_path(@team), class: 'btn btn-default' %>
  <h3>負担指数</h3>
  <%= bar_chart @graphys %>
</div>

app/views/reports/new.html.erb
<div class="container_position">
  <div class="container">
    <div class="contents">
      <h3>レポートを作成する</h3><br>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<div class="container_position">
  <div class="container">
    <div class="contents">
      <h3 id="report-show_index">レポート詳細画面</h3>
        <br>
        <p>投稿者:<%= @report.user.name %></p>
        <p>タイトル: <%= @report.title %></p>
        <p>内容: <%= @report.content %></p>
        <p>実施日: <%= @report.date %></p>
        <p>場所: <%= @report.place %></p>
        <p>所要時間: <%= @report.time %>時間</p>
        <p>所要合算: <%= @total_time %>時間</p>
        <p>画像:<%= image_tag(@report.image.url) if @report.image && @report.image.url %></p>
    <% if @report.user.id == current_user.id %>
    <% end %>
    <hr>
      <div id="report_comments_area">
        <h3>コメント一覧</h3>
        <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
        <%= render partial: 'report_comments/index', locals: { report_comments: @report_comments, report: @report } %>
      </div><br>
      <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
      <%= render partial: 'report_comments/form', locals: { report_comment: @report_comment, report: @report } %>
   </div>
  </div>
</div>