config/routes.rb
Rails.application.routes.draw do
  get 'assigns/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  resources :users, only: [:create, :show, :edit, :update]

  root 'top#index'

  resources :teams, shallow: true do
    resources :assigns
    member do
       get :invite
       post :invite_mail
    end
  end

  resources :reports, only: [] do
    resources :report_comments, only: [:create, :destroy, :edit, :update]
    #   collection do
    #   post :confirm
    # end
  end

  resources :teams do
    resources :reports do
      post :confirm, on: :collection # on: :member
    end
  end

  resources :assigns

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>share work PTA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Share_Work_PTA</span>
            <% if user_signed_in? %>
              <% if current_user.leader? %>
                <span class="icon-bar"><%= link_to 'チームを作成する', teams_path %></span>
              <% end %>
                <span class="icon-bar"><%= link_to "チーム一覧", teams_path %></span>
                <span class="icon-bar"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></span>
                <span class="icon-bar"><%= link_to "マイページ", user_path(current_user.id) %></span>
              <% else %>
                <span class="icon-bar"><%= link_to "新規登録", new_user_registration_path %></span>
                <span class="icon-bar"><%= link_to "ログイン", new_user_session_path %></span>
              <% end %>
          </button>-->
          <a class="navbar-brand">share work PTA</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <% if current_user.leader? %>
                <li><%= link_to 'チームを作成する', teams_path %></li>
              <% end %>
                <li><%= link_to "チーム一覧", teams_path %></li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, id: "sessions-logout__part" %>
                </li>
                <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <% else %>
                <li><%= link_to "新規登録", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
              <% end %>
          </ul>
        </div>
      </nav>
      <div class="container_position">
        <% if notice %>
          <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </body>
      <!-- <footer>
        <p>By share work PTA</p>
      </footer> -->
</html>